### ISSUE TITLE
combine_homology error

### ISSUE THREAD

**Issue by wharvey31** [marschall-lab/strand-seq-graph-phasing#29]
Hello,

I am having a hard time understanding an error in this pipeline on the combine_homology step. The error is as follows:

```
Error in `mutate()`:
ℹ In argument: `bubble = paste0("bubble_", 1:n())`.
Caused by error:
! `bubble` must be size 0 or 1, not 2.
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─tidyr::pivot_longer(...)
  4. ├─dplyr::mutate(., bubble = paste0("bubble_", 1:n()))
  5. ├─dplyr:::mutate.data.frame(., bubble = paste0("bubble_", 1:n()))
  6. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  7. │   ├─base::withCallingHandlers(...)
  8. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  9. │     └─mask$eval_all_mutate(quo)
 10. │       └─dplyr (local) eval()
 11. ├─dplyr:::dplyr_internal_error(...)
 12. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
 13. │   └─rlang:::signal_abort(cnd, .file)
 14. │     └─base::signalCondition(cnd)
 15. └─dplyr (local) `<fn>`(`<dpl:::__>`)
 16.   └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted
```

Let me know if you need any input files from me and I can publicly list them. Thanks!

**Comment by lincolnsotto** [comment]
Hi, thank for your question.
If you would like write "bubble_" in whole of column why did you do (1:n())?
Maybe you would must do it: bubble = paste0("bubble_", name_of_your_column)

**Comment by mir-cat** [comment]
Hi @wharvey31 I am curious as to why the combine homology rule is running for you ~ those rules are "vestigial" in the sense that they haven't been deleted yet from the pipeline, but I believe that I modified the pipeline such that they aren't needed for any of the main outputs of the pipeline, and thus on a default run the homology rules shouldn't run at all. Do you need those files for some other purpose? I can also take a look at the input files, in case that would be helpful to you.

**Comment by wharvey31** [comment]
Is it possible that this rule has not be made "vestigial" for the hifiasm segment of the pipeline? I have attached my rulegraph pdf for input with only hifiasm assemblies. It seems like it still contains this step on the way to the yak_count_split_fasta rule.

[rulegraph.pdf](https://github.com/marschall-lab/strand-seq-graph-phasing/files/12705047/rulegraph.pdf)

**Comment by mir-cat** [comment]
I just checked and in the most recent dev branch release (v0.3.1-alpha) the `count_haplotype_markers` and `fudge_haplotype_markers` rules no longer take as input the output of `combine homology` Is that rulegraph based on an older version of the pipeline?

**Comment by wharvey31** [comment]
Thanks for confirming this Mir. I was on the older version of the pipeline for sure. Our cluster has been out of commission this week, so I am unable to test the newest version, but will open another ticket if something doesn't work.
