### ISSUE TITLE
Error with count_sseq_alignments

### ISSUE THREAD

**Issue by wharvey31** [marschall-lab/strand-seq-graph-phasing#30]
Hello,

I am having experiencing errors for the rule count_sseq_alignments:

```
counting bwa-mem alignments in 000095.mdup.bam 
counting bwa-fastmap alignments in 000000_maximal_unique_exact_match.tsv 
Error in `import_mapper()`:
ℹ In index: 1.
Caused by error in `UseMethod()`:
! no applicable method for 'collector_value' applied to an object of class "c('collector_skip', 'collector')"
Backtrace:
     ▆
  1. ├─purrr (local) import_mapper(...)
  2. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  3. │   ├─purrr:::with_indexed_errors(...)
  4. │   │ └─base::withCallingHandlers(...)
  5. │   ├─purrr:::call_with_cleanup(...)
  6. │   └─global .f(.x[[i]], ...)
  7. │     └─global extract_exact_matches(x)
  8. │       └─readr::read_tsv(...)
[count_sseq_alignments_NA18989.log](https://github.com/marschall-lab/strand-seq-graph-phasing/files/12784477/count_sseq_alignments_NA18989.log)

  9. │         └─vroom::vroom(...)
 10. │           └─vroom:::collector_value(cols[[i]])
 11. └─base::.handleSimpleError(...)
 12.   └─purrr (local) h(simpleError(msg, call))
 13.     └─cli::cli_abort(...)
 14.       └─rlang::abort(...)
Execution halted
```

I have attached the complete log and the 000000_maximal_unique_exact_match.tsv file which it seems to struggle to read. 

[count_sseq_files.tar.gz](https://github.com/marschall-lab/strand-seq-graph-phasing/files/12784491/count_sseq_files.tar.gz)

**Comment by mir-cat** [comment]
hi, I believe that this error is arising because there are no valid matches found in `000000_maximal_unique_exact_match.tsv ` for the import function to extract (No lines starting with 'EM'). I will take a look at fixing this, but I am also quite surprised, as when I ran this sample with the verkko graphs, matches were found. Do you have any other samples/libraries with no valid matches?

**Comment by mir-cat** [comment]
@wharvey31 I created a hotfix in a hotfix branch here: https://github.com/marschall-lab/strand-seq-graph-phasing/tree/hotfix does that fix the issue for you?

**Comment by wharvey31** [comment]
Thanks for the response on this. I do have lines with EM in them, but apparently not in every file. 

I switched to the hotfix branch and we are on to a new step/error. This one is conda env related, so I think I can work through it. I will append the pull request I have out to include whatever changes I find necessary here.
