### ISSUE TITLE
count_haplotype_markers

### ISSUE THREAD

**Issue by wharvey31** [marschall-lab/strand-seq-graph-phasing#31]
Me again. 

This time in count_haplotype_markers

```
Running contiBAIT QC
-> Checking for high quality libraries
    -> 000007 has insufficient reads. Removing
    -> 000019 has insufficient reads. Removing
    -> 000039 has insufficient reads. Removing
    -> 000061 has insufficient reads. Removing
-> Removed 4 libraries from a total of 82. 78 remaining (95.1%)
-> Computing QA measures for contigs and sorting by best quality first
Error in contigAgreement * contigNAs : 
  non-numeric argument to binary operator
Calls: preprocessStrandTable -> preprocessStrandTable -> .local
Execution halted
```

Input files and log attached.

[count_haplotype_markers.tar.gz](https://github.com/marschall-lab/strand-seq-graph-phasing/files/12785794/count_haplotype_markers.tar.gz)

**Comment by mir-cat** [comment]
Hi so this issue appears to be arising from the fact that every library for every graph unitig appears to have a WC library state. The contiBAIT preprocessing function appears to expect at least some libs/unitigs in WW/CC state, and errors out accordingly. However, this isn't something that I can bugfix/code around; when every lib/unitig appears to be WC like this, it makes the clustering by chromosome impossible, and thus the phasing won't work.

More "generally" worrisome is the fact that this appears to be the second issue stemming from poor alignments of the sseq reads to the graph, like #30 which had a library with no fastmap hits for hifiasm, but had hits for the verkko graph. Are the hifiasm graphs particularly fragmented, which may lead to poor alignments from the Strand-seq reads? Is there possibly something going on with the input?

**Comment by mir-cat** [comment]
This image shows a distribution of Strand-seq library frequencies for NA19836 for the verkko graph:

![image](https://github.com/marschall-lab/strand-seq-graph-phasing/assets/10320217/c12f4f0d-7bbf-4320-b802-b07306d1790c)

Notice the three peaks in the distribution, one at either extreme for the WW and CC strand states, and one in the middle for WC strand states.

Here is the same graph for the NA19836 hifiasm sample you shared

![image](https://github.com/marschall-lab/strand-seq-graph-phasing/assets/10320217/db119a27-cac1-437b-b5db-c0a9554ed71e)

No peaks at the extremes, only one in the middle

**Comment by wharvey31** [comment]
Thanks for the visualization Mir and the pursuit of the issue. 

I guess there are two things which could be happening here: either my input StrandSeq data is incorrect or the assembly file I am using is incorrect. Can you confirm that you have used the gfa ending with: `.hifiasm.bp.p_utg.gfa` in the past?

I believe this to be the case based on prior communications, but would like to confirm. I will do some checks on the input data to see if I can see anything awry there.

**Comment by mir-cat** [comment]
I can confirm that the gfa that I have used in the past for hifiasm is `.hifiasm.bp.p_utg.gfa`

**Comment by wharvey31** [comment]
Thanks @mir-cat. I have corrected the strandseq data which I was using and that helped. I do have some new errors incoming though, but I will open up new issues.
