### ISSUE TITLE
count_haplotypes hclust

### ISSUE THREAD

**Issue by wharvey31** [marschall-lab/strand-seq-graph-phasing#32]
Hi @mir-cat,

I have successfully processed about 3 dozen samples with this pipeline. Thanks for your help getting to this point. I have two samples which have stalled at the count_haplotypes step. An example of the log output is:

```
No. PAR clusters detected:  0 
Joining with `by = join_by(unitig)`
Detecting unitig orientation
There were 25 warnings (use warnings() to see them)
Error in `map()`:
ℹ In index: 24.
ℹ With name: LGNA_utg001299l.
Caused by error in `hclust()`:
! must have n >= 2 objects to cluster
Backtrace:
     ▆
  1. ├─purrr::map(...)
  2. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  3. │   ├─purrr:::with_indexed_errors(...)
  4. │   │ └─base::withCallingHandlers(...)
  5. │   ├─purrr:::call_with_cleanup(...)
  6. │   └─global .f(.x[[i]], ...)
  7. │     ├─hclust(x, method = "complete") %>% cutree(k = 2)
  8. │     └─stats::hclust(x, method = "complete")
  9. │       └─base::stop("must have n >= 2 objects to cluster")
 10. ├─stats::cutree(., k = 2)
 11. │ └─base::nrow(tree$merge)
 12. └─base::.handleSimpleError(...)
 13.   └─purrr (local) h(simpleError(msg, call))
 14.     └─cli::cli_abort(...)
 15.       └─rlang::abort(...)
Execution halted
```

Both seem to be at the exact same spot. I have attached tar archives with input files and logs. Thanks so much!

[NA19983_count_haplotypes.tar.gz](https://github.com/marschall-lab/strand-seq-graph-phasing/files/12937623/NA19983_count_haplotypes.tar.gz)

[HG01114_count_haplotypes.tar.gz](https://github.com/marschall-lab/strand-seq-graph-phasing/files/12937625/HG01114_count_haplotypes.tar.gz)

**Comment by mir-cat** [comment]
Just pushed to the hotfix branch let me know if it fixes things on your end.
