### ISSUE TITLE
v0.3.1-alpha: isolate env setup

### ISSUE THREAD

**Issue by ptrebert** [marschall-lab/strand-seq-graph-phasing#40]
Given that there is a hard need for manual setup step (= BubbleGun) if the environment is not online, the env setup should be isolated as a separate rule to run or similar; i.e., this shouldn't require a complete config specification etc.

**Comment by mir-cat** [comment]
As mentioned in #42, the bubblegun step is vestigial, and references to it will be removed in a future version of the pipeline
