### ISSUE TITLE
v0.3.1-alpha: env setup is generally faulty

### ISSUE THREAD

**Issue by ptrebert** [marschall-lab/strand-seq-graph-phasing#43]
Following the readme instructions, the env setup is generally incomplete, e.g., the BubbleGun environment is not created after starting the workflow with the default target (= first rule in the Snakefile) and `--conda-create-envs-only`.

Logically, only that can be the cause:

```
if reference:
    ALL_OUTPUT.append(expand("reference_alignments/{ref_name}/{sample}_{ref_name}_ref-aln.paf", sample=SAMPLES, ref_name=ref_name))

rule all:
    input:
        sample_sheet=ALL_OUTPUT,
        breakpoints=expand("breakpoints/{sample}_breakpoint_windows.csv", sample=SAMPLES)
```

The `ALL_OUTPUT` does not represent the entire (all) output of the pipeline, but only the reference alignments. The breakpoint windows do not seem to require the execution of BubbleGun (and potentially other parts of the pipeline, I haven't checked that).

**Comment by mir-cat** [comment]
so most of ALL_OUTPUT is handled in [rules/collect_output.smk](https://github.com/marschall-lab/strand-seq-graph-phasing/blob/dev/workflow/rules/collect_output.smk), and does not represent just the reference alignments, but different outputs based on verrko/hifiasm. The logic around whether the breakpoints or reference are included in the output files are something that I have been working on, and in the near future there will be a config option for both of those outputs.

For bubblegun, I mentioned in #42 that the package is vestigial and references to it will be removed in the future.
