### ISSUE TITLE
update readme to use snakemake runner yaml

### ISSUE THREAD

**Issue by ptrebert** [marschall-lab/strand-seq-graph-phasing#9]
This env file should be used in the central readme to lower the risk of users running with environments containing incompatible software (can happen easily with Snakemake)

https://github.com/marschall-lab/strand-seq-graph-phasing/blob/e70317340f40f83546b314b5cb473173802eeed7/workflow/envs/env_snakemake.yaml#L4

**Comment by mir-cat** [comment]
Also update readme to describe parameters (from #5)
